102 and 103 ready for use
Amybough/Tests pull request #5
Opened 2021-08-12 15:18 UTC by depa02

2021-08-26 10:09 UTC, flopezag requested changes

2021-08-26 10:09 UTC, flopezag commented on features/steps/101.Getting_Started_steps.py
> +                f'(depa) Response from CB test execution does not match the tutorial expected HTTP response body:\n  {diff}')
I think that it is not needed to put (depa) in the message

2021-08-26 10:09 UTC, flopezag commented on README.md
> +3. Activate the python environment: `source ./venv/bin/activate` (depa\'s laptop --> source .venv/bin/activate)
It sounds a problem in the execution of virtualenv, I suggest to check the permissions of the script. Regarding the documentation, I think that it is not needed to put that comments

    (depa\'s laptop --> python3 -m virtualenv .venv)
    (depa\'s laptop --> python3 -m virtualenv .venv)

2021-08-26 10:22 UTC, depa02 commented on features/steps/101.Getting_Started_steps.py
> +                f'(depa) Response from CB test execution does not match the tutorial expected HTTP response body:\n  {diff}')
agree

2021-08-26 10:27 UTC, depa02 commented on README.md
> +3. Activate the python environment: `source ./venv/bin/activate` (depa\'s laptop --> source .venv/bin/activate)
i need them. so perhaps we may say:
"alternatively steps 2 and 3 can be executed as:
2. Create the virtualenv: `python3 -m virtualenv .venv`
3. Activate the python environment: `source .venv/bin/activate`"

what do you think?

2022-01-17 11:49 UTC, flopezag commented on README.md
> +3. Activate the python environment: `source ./venv/bin/activate` (depa\'s laptop --> source .venv/bin/activate)
I think that this a problem in the configuration of virtualenv in your local environment, but it should not be detailed in the README.

2022-01-17 11:51 UTC, flopezag requested changes

2022-01-17 11:51 UTC, flopezag commented on features/steps/101.Getting_Started_steps.py
> +                f'(depa) Response from CB test execution does not match the tutorial expected HTTP response body:\n  {diff}')
still pending to make a new commit of the file without this text

2022-03-09 17:43 UTC, flopezag approved these changes

2022-03-09 17:44 UTC, merged